name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - cartopy
  - cdsapi
  - cftime
  - eccodes
  - geopy
  - geos
  - h5py
  - matplotlib
  - netcdf4
  - numpy
  - rasterio
  - requests
  - rioxarray
  - scipy
  - shapely
  - xarray
  - cfgrib
  - scikit-image
